[package]
name = "ToolBox"
version = "0.1.0"
authors = ["Hrithik <wandererassociation@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
ratatui = { version = "0.29.0", features = ["crossterm"] }
crossterm = "0.29.0"
color-eyre = "0.6.5"
